"use client";

import Link from "next/link";
import { Bookmark, ChevronRight, Clock3, Target, TrendingUp } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { DailyActivity, Question, Subject, Topic, TopicStats } from "@/lib/types";
import { torontoDateKey } from "@/lib/utils";

export function StatsView({ subjects, topics, stats, activity, flagged }: { subjects: Subject[]; topics: Topic[]; stats: TopicStats[]; activity: DailyActivity[]; flagged: Question[] }) {
  const lineData = activity.reduce<{ week: string; accuracy: number; attempted: number }[]>((weeks, day, index) => { if (index % 7 === 6) { const slice = activity.slice(index - 6, index + 1); const attempted = slice.reduce((sum, item) => sum + item.attempted, 0); const correct = slice.reduce((sum, item) => sum + item.correct, 0); weeks.push({ week: `W${weeks.length + 1}`, accuracy: attempted ? Math.round(correct / attempted * 100) : 0, attempted }); } return weeks; }, []);
  const totals = stats.reduce((acc, item) => ({ attempted: acc.attempted + item.attempted, correct: acc.correct + item.correct, time: acc.time + item.avgTimeMs * item.attempted }), { attempted: 0, correct: 0, time: 0 });
  const overall = totals.attempted ? Math.round((totals.correct / totals.attempted) * 100) : 0;
  const avgSec = totals.attempted ? Math.round(totals.time / totals.attempted / 1000) : 0;
  const todayKey = torontoDateKey();
  const monthKey = todayKey.slice(0, 7);
  const lastMonthKey = torontoDateKey(new Date(`${todayKey.slice(0, 7)}-01T12:00:00Z`).getTime() - 86_400_000).slice(0, 7);
  const thisMonth = activity.filter((day) => day.date.startsWith(monthKey)).reduce((sum, day) => sum + day.attempted, 0);
  const lastMonth = activity.filter((day) => day.date.startsWith(lastMonthKey)).reduce((sum, day) => sum + day.attempted, 0);
  const last30 = activity.slice(-30), prev30 = activity.slice(-60, -30);
  const acc = (days: DailyActivity[]) => { const a = days.reduce((s, d) => s + d.attempted, 0); return a ? Math.round(days.reduce((s, d) => s + d.correct, 0) / a * 100) : null; };
  const delta = acc(last30) !== null && acc(prev30) !== null ? (acc(last30) as number) - (acc(prev30) as number) : null;
  const trend = lineData.length >= 2 ? lineData[lineData.length - 1].accuracy - lineData[0].accuracy : 0;
  const statFor = (id: string) => stats.find((item) => item.topicId === id);
  const nameTopic = (id: string) => topics.find((item) => item.id === id)?.name ?? id;
  return (
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 md:px-8 md:py-8">
      <PageHeader eyebrow="Performance" title="Your statistics" description="Use trends to choose the next topic, not to judge the last session." />
      <div className="grid gap-4 sm:grid-cols-3">{[{ icon: Target, label: "Overall accuracy", value: `${overall}%`, detail: delta === null ? `${totals.attempted} attempted` : `${delta >= 0 ? "+" : ""}${delta}% vs previous 30 days`, color: "text-emerald-600" }, { icon: Clock3, label: "Average response", value: `${avgSec} sec`, detail: "per question", color: "text-cyan-600" }, { icon: TrendingUp, label: "Questions this month", value: thisMonth.toLocaleString(), detail: `${lastMonth.toLocaleString()} last month`, color: "text-violet-600" }].map(({ icon: Icon, label, value, detail, color }) => <Card key={label}><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><div className={`grid size-10 place-items-center rounded-xl bg-muted ${color}`}><Icon className="size-5" /></div></CardContent></Card>)}</div>
      <Card className="mt-5"><CardHeader><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><CardTitle className="text-lg">Accuracy over time</CardTitle><p className="mt-1 text-xs text-muted-foreground">Weekly accuracy across the last 12 weeks</p></div>{lineData.length >= 2 && <Badge className="w-fit bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"><TrendingUp />{trend >= 0 ? "Improving" : "Slipping"}</Badge>}</div></CardHeader><CardContent className="h-[300px] pt-2"><div aria-hidden="true" className="h-full"><ResponsiveContainer width="100%" height="100%"><LineChart accessibilityLayer={false} data={lineData} margin={{ left: -12, right: 12, top: 5 }}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={0.25} /><XAxis dataKey="week" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={{ borderRadius: 12, fontSize: 12 }} formatter={(value, name) => [name === "accuracy" ? `${value}%` : value, name === "accuracy" ? "Accuracy" : "Attempted"]} /><Line type="monotone" dataKey="accuracy" stroke="#059669" strokeWidth={3} dot={{ r: 3, fill: "#059669" }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div><table className="sr-only"><caption>Weekly accuracy for the last 12 weeks</caption><thead><tr><th>Week</th><th>Attempted</th><th>Accuracy</th></tr></thead><tbody>{lineData.map((week) => <tr key={week.week}><td>{week.week}</td><td>{week.attempted}</td><td>{week.attempted ? `${week.accuracy}%` : "No attempts"}</td></tr>)}</tbody></table></CardContent></Card>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_360px]">
        <Card><CardHeader><CardTitle className="text-lg">Subject and topic performance</CardTitle><p className="text-xs text-muted-foreground">Attempted questions, accuracy, and average response time</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="pl-6">Subject / topic</TableHead><TableHead>Attempted</TableHead><TableHead>Accuracy</TableHead><TableHead className="pr-6 text-right">Avg. time</TableHead></TableRow></TableHeader><TableBody>{subjects.flatMap((subject) => { const childTopics = topics.filter((topic) => topic.subjectId === subject.id); const topicRows = childTopics.map((topic) => { const item = statFor(topic.id); const attempted = item?.attempted ?? 0; const accuracy = attempted ? Math.round((item?.correct ?? 0) / attempted * 100) : 0; return <TableRow key={topic.id}><TableCell className="pl-10 text-sm">{topic.name}</TableCell><TableCell className="text-sm">{attempted}</TableCell><TableCell><div className="flex min-w-32 items-center gap-3"><Progress value={accuracy} aria-label={`${topic.name} accuracy`} className="h-1.5 flex-1" /><span className="w-9 text-right text-xs font-medium">{accuracy}%</span></div></TableCell><TableCell className="pr-6 text-right text-sm text-muted-foreground">{Math.round((item?.avgTimeMs ?? 0) / 1000)} sec</TableCell></TableRow>; }); return [<TableRow key={`${subject.id}-header`} className="bg-muted/40"><TableCell className="pl-6 font-semibold">{subject.name}</TableCell><TableCell colSpan={3} className="text-xs text-muted-foreground">{childTopics.length} tracked topics</TableCell></TableRow>, ...topicRows]; })}</TableBody></Table></div></CardContent></Card>
        <Card className="self-start"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-lg">Flagged questions</CardTitle><p className="mt-1 text-xs text-muted-foreground">Ready for another look</p></div><div className="grid size-9 place-items-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300"><Bookmark className="size-4 fill-current" /></div></div></CardHeader><CardContent className="space-y-2">{flagged.length === 0 && <p className="text-sm text-muted-foreground">Flag a question during a session and it will show up here.</p>}{flagged.map((question) => <Link prefetch={false} key={question.id} href={`/api/practice/${question.qid}`} className="group block rounded-xl border p-3.5 transition-colors hover:border-amber-300 hover:bg-amber-50/40 dark:hover:bg-amber-950/20"><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted text-[10px] font-semibold">{question.qid}</span><div className="min-w-0 flex-1"><p className="line-clamp-2 text-xs font-medium leading-5">{question.stem}</p><p className="mt-1 text-[11px] text-muted-foreground">{nameTopic(question.topicId)}</p></div><ChevronRight className="mt-1 size-4 shrink-0 text-muted-foreground group-hover:text-amber-700" /></div></Link>)}<Link href="/questions?status=flagged" className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-emerald-700 dark:text-emerald-400">Browse all flagged <ChevronRight className="size-4" /></Link></CardContent></Card>
      </div>
    </div>
  );
}
