import type { Attempt, DashboardStats, Question, QuestionStatus, Session, Subject, Topic, TopicStats } from "@/lib/types";

export const subjects: Subject[] = [
  { id: "pediatrics", name: "Pediatrics", questionCount: 591 },
  { id: "psychiatry", name: "Psychiatry", questionCount: 406 },
  { id: "medicine", name: "Medicine", questionCount: 335 },
  { id: "pmch", name: "PMCH", questionCount: 321 },
  { id: "surgery", name: "Surgery", questionCount: 30 },
];

export const topics: Topic[] = [
  { id: "ped-cardio", subjectId: "pediatrics", name: "Cardiology", questionCount: 82 },
  { id: "ped-infectious", subjectId: "pediatrics", name: "Infectious Disease", questionCount: 104 },
  { id: "ped-development", subjectId: "pediatrics", name: "Development", questionCount: 71 },
  { id: "psych-mood", subjectId: "psychiatry", name: "Mood Disorders", questionCount: 94 },
  { id: "psych-psychosis", subjectId: "psychiatry", name: "Psychotic Disorders", questionCount: 68 },
  { id: "psych-substance", subjectId: "psychiatry", name: "Substance Use", questionCount: 52 },
  { id: "med-cardio", subjectId: "medicine", name: "Cardiology", questionCount: 79 },
  { id: "med-resp", subjectId: "medicine", name: "Respirology", questionCount: 62 },
  { id: "med-endo", subjectId: "medicine", name: "Endocrinology", questionCount: 55 },
  { id: "pmch-screening", subjectId: "pmch", name: "Screening", questionCount: 63 },
  { id: "pmch-epi", subjectId: "pmch", name: "Epidemiology", questionCount: 72 },
  { id: "pmch-ethics", subjectId: "pmch", name: "Ethics", questionCount: 58 },
  { id: "surg-trauma", subjectId: "surgery", name: "Trauma", questionCount: 11 },
  { id: "surg-abdo", subjectId: "surgery", name: "Acute Abdomen", questionCount: 10 },
  { id: "surg-postop", subjectId: "surgery", name: "Perioperative Care", questionCount: 9 },
];

export const questions: Question[] = [
  { id: "q1", qid: 1001, subjectId: "pediatrics", topicId: "ped-cardio", stem: "A 6-year-old child is found to have a grade 2 systolic murmur during a routine visit. She is active, growing normally, and has no cardiac symptoms. The murmur becomes softer when she stands. Which finding most supports an innocent murmur?", options: ["A diastolic component", "Radiation to the back", "A soft, position-dependent systolic sound", "A palpable thrill", "Associated cyanosis"], answerIdx: 2, explanation: ["Innocent murmurs are typically soft, systolic, localized, and sensitive to position.", "Standing reduces venous return and often makes an innocent Still murmur quieter.", "Diastolic murmurs, thrills, cyanosis, or concerning radiation warrant further assessment."] },
  { id: "q2", qid: 1002, subjectId: "pediatrics", topicId: "ped-infectious", stem: "A 3-year-old has fever, barking cough, inspiratory stridor, and hoarseness that worsens at night. There is no drooling, and the child can swallow. What is the most appropriate initial treatment?", options: ["Oral amoxicillin", "Dexamethasone", "Immediate bronchoscopy", "Ribavirin", "Racemic epinephrine only"], answerIdx: 1, explanation: ["This presentation is typical of viral croup.", "A single dose of dexamethasone is recommended for croup of any severity.", "Nebulized epinephrine is added for moderate or severe respiratory distress."] },
  { id: "q3", qid: 1003, subjectId: "pediatrics", topicId: "ped-development", stem: "At an 18-month well-child visit, a toddler walks independently, uses 8 words, points to show interest, and follows one-step commands. Which developmental domain should be monitored most closely?", options: ["Gross motor", "Fine motor", "Expressive language", "Social interaction", "Receptive language"], answerIdx: 2, explanation: ["By 18 months, many children use at least 10 to 25 words.", "This child has age-appropriate walking, joint attention, and comprehension.", "Developmental milestones vary, but expressive language should be reassessed and hearing considered."] },
  { id: "q4", qid: 1004, subjectId: "psychiatry", topicId: "psych-mood", stem: "A 32-year-old has 6 weeks of low mood, anhedonia, early-morning awakening, poor concentration, and guilt. There is no history of mania or substance use. Which treatment is an appropriate first-line option?", options: ["Lithium alone", "Cognitive behavioural therapy", "Haloperidol", "Electroconvulsive therapy only", "Reassurance without follow-up"], answerIdx: 1, explanation: ["The symptoms meet criteria for a major depressive episode.", "Psychotherapy such as cognitive behavioural therapy and antidepressant medication are first-line options depending on severity and preference.", "A bipolar history must always be screened for before starting treatment."] },
  { id: "q5", qid: 1005, subjectId: "psychiatry", topicId: "psych-psychosis", stem: "A 24-year-old reports voices commenting on his actions for 8 months, social withdrawal, and declining function. Substance screening is negative. Which diagnosis is most likely?", options: ["Brief psychotic disorder", "Schizophreniform disorder", "Schizophrenia", "Delusional disorder", "Schizoaffective disorder"], answerIdx: 2, explanation: ["Schizophrenia requires characteristic symptoms with continuous disturbance for at least 6 months and functional decline.", "Schizophreniform disorder lasts 1 to 6 months.", "There is no prominent mood syndrome here to suggest schizoaffective disorder."] },
  { id: "q6", qid: 1006, subjectId: "psychiatry", topicId: "psych-substance", stem: "A hospitalized patient becomes tremulous, diaphoretic, anxious, and tachycardic 18 hours after admission. He drinks 8 beers daily. What is the best initial pharmacologic management?", options: ["Naloxone", "Lorazepam", "Haloperidol monotherapy", "Methadone", "Disulfiram"], answerIdx: 1, explanation: ["The timing and autonomic hyperactivity suggest alcohol withdrawal.", "A benzodiazepine guided by symptom severity is first-line treatment.", "Thiamine should be given before or with glucose when deficiency is possible."] },
  { id: "q7", qid: 1007, subjectId: "medicine", topicId: "med-cardio", stem: "A 67-year-old with crushing substernal chest pain has ST elevation in leads II, III, and aVF. Blood pressure is 86/58 mm Hg and the lungs are clear. Which additional finding is most likely?", options: ["Pulmonary edema", "Elevated jugular venous pressure", "Wide pulse pressure", "Bilateral carotid bruits", "Pulsus paradoxus"], answerIdx: 1, explanation: ["An inferior myocardial infarction can involve the right ventricle.", "Right ventricular infarction causes hypotension, elevated jugular venous pressure, and clear lungs.", "Nitrates can worsen preload-dependent hypotension in this setting."] },
  { id: "q8", qid: 1008, subjectId: "medicine", topicId: "med-resp", stem: "A 58-year-old smoker has progressive exertional dyspnea. Spirometry shows an FEV1/FVC ratio of 0.58 that remains reduced after bronchodilator. What pattern does this demonstrate?", options: ["Restrictive lung disease", "Fixed upper airway obstruction", "Obstructive lung disease", "Normal aging", "Neuromuscular weakness"], answerIdx: 2, explanation: ["A persistently reduced FEV1/FVC ratio indicates airflow obstruction.", "In a smoker with progressive symptoms, COPD is likely.", "Restriction is suggested by reduced lung volumes with a preserved or increased ratio."] },
  { id: "q9", qid: 1009, subjectId: "medicine", topicId: "med-endo", stem: "A 45-year-old with type 2 diabetes has an eGFR of 78 mL/min and persistent albuminuria. Blood pressure is 146/88 mm Hg. Which medication best addresses both renal protection and blood pressure?", options: ["Amlodipine", "Hydrochlorothiazide", "Ramipril", "Metoprolol", "Doxazosin"], answerIdx: 2, explanation: ["An ACE inhibitor is recommended for hypertension with diabetic albuminuria.", "It lowers intraglomerular pressure and slows progression of kidney disease.", "Creatinine and potassium should be monitored after initiation."] },
  { id: "q10", qid: 1010, subjectId: "pmch", topicId: "pmch-screening", stem: "A screening test has high sensitivity but modest specificity. What is the main consequence when it is used in a low-prevalence population?", options: ["More false-negative results", "More false-positive results", "Higher positive predictive value", "Lower negative predictive value", "No change in predictive values"], answerIdx: 1, explanation: ["When prevalence is low, a larger proportion of positive results are false positives.", "Positive predictive value falls as disease prevalence falls.", "High sensitivity supports a strong negative predictive value."] },
  { id: "q11", qid: 1011, subjectId: "pmch", topicId: "pmch-epi", stem: "In a cohort study, 40 of 200 exposed participants develop disease compared with 20 of 400 unexposed participants. What is the relative risk?", options: ["0.25", "0.5", "2", "4", "8"], answerIdx: 3, explanation: ["Risk in exposed participants is 40/200, or 0.20.", "Risk in unexposed participants is 20/400, or 0.05.", "Relative risk is 0.20 divided by 0.05, which equals 4."] },
  { id: "q12", qid: 1012, subjectId: "pmch", topicId: "pmch-ethics", stem: "A competent adult refuses a recommended blood transfusion after receiving clear information about the risks. The physician believes the refusal may be fatal. What is the most appropriate next step?", options: ["Obtain a court order", "Transfuse based on beneficence", "Respect the informed refusal", "Ask family to override the decision", "Declare the patient incapable"], answerIdx: 2, explanation: ["A capable adult may refuse treatment, even when the decision carries serious risk.", "The physician should confirm capacity, understanding, and voluntariness, then document the discussion.", "Disagreement with a decision does not establish incapacity."] },
  { id: "q13", qid: 1013, subjectId: "surgery", topicId: "surg-trauma", stem: "A patient arrives after a motor vehicle collision with hypotension, distended neck veins, and absent breath sounds on the right. What is the immediate management?", options: ["Chest CT", "Needle decompression", "Pericardiocentesis", "Bronchoscopy", "Observation"], answerIdx: 1, explanation: ["The findings indicate tension pneumothorax with obstructive shock.", "Immediate decompression must not wait for imaging.", "Definitive tube thoracostomy follows emergency decompression."] },
  { id: "q14", qid: 1014, subjectId: "surgery", topicId: "surg-abdo", stem: "A 19-year-old has periumbilical pain that migrated to the right lower quadrant, anorexia, and fever. Which physical finding most supports the leading diagnosis?", options: ["Murphy sign", "Tenderness at McBurney point", "Cullen sign", "Shifting dullness", "Costovertebral angle tenderness"], answerIdx: 1, explanation: ["Migrating pain, anorexia, fever, and right lower quadrant tenderness suggest acute appendicitis.", "McBurney point tenderness is a classic localizing finding.", "Imaging choice depends on age, pregnancy status, and clinical uncertainty."] },
  { id: "q15", qid: 1015, subjectId: "surgery", topicId: "surg-postop", stem: "On postoperative day 1 after abdominal surgery, a patient has a temperature of 38.1 C and mild bibasilar crackles. He is hemodynamically stable. What is the best initial approach?", options: ["Broad-spectrum antibiotics", "Immediate CT abdomen", "Mobilization and lung expansion exercises", "Return to the operating room", "Therapeutic anticoagulation"], answerIdx: 2, explanation: ["Early low-grade postoperative fever is often an inflammatory response and may accompany shallow breathing.", "Mobilization, analgesia, and lung expansion exercises are appropriate initial measures in a stable patient.", "Targeted investigation is guided by symptoms and persistence."] },
  { id: "q16", qid: 1016, subjectId: "pediatrics", topicId: "ped-infectious", stem: "A 7-month-old has rhinorrhea, cough, wheeze, and increased work of breathing. Oxygen saturation is 95% on room air and feeding is mildly reduced. Which management is most appropriate?", options: ["Routine salbutamol", "Supportive care", "Oral corticosteroids", "Antibiotics", "Chest physiotherapy"], answerIdx: 1, explanation: ["This is uncomplicated viral bronchiolitis.", "Supportive care with hydration, nasal suction, and monitoring is the mainstay.", "Bronchodilators, corticosteroids, antibiotics, and chest physiotherapy are not routinely recommended."] },
  { id: "q17", qid: 1017, subjectId: "pediatrics", topicId: "ped-cardio", stem: "A newborn becomes cyanotic during feeding. Oxygen saturation improves little with supplemental oxygen. Which mechanism best explains the finding?", options: ["Right-to-left cardiac shunting", "Iron deficiency", "Left-to-right shunting only", "Physiologic anemia", "Upper airway congestion"], answerIdx: 0, explanation: ["Cyanosis that responds poorly to oxygen suggests a right-to-left shunt or severe pulmonary disease.", "Critical congenital heart disease must be assessed urgently.", "Left-to-right shunts do not typically cause early cyanosis."] },
  { id: "q18", qid: 1018, subjectId: "pediatrics", topicId: "ped-development", stem: "A 4-year-old speaks in full sentences, draws a person with three parts, and plays cooperatively. Which additional skill is expected at this age?", options: ["Sits without support", "Uses a pincer grasp", "Hops on one foot", "Reads paragraphs", "Ties shoelaces reliably"], answerIdx: 2, explanation: ["Hopping on one foot is a typical gross motor milestone around age 4.", "The other early motor skills are achieved in infancy.", "Reading paragraphs and reliably tying shoelaces are generally later skills."] },
  { id: "q19", qid: 1019, subjectId: "psychiatry", topicId: "psych-mood", stem: "A 29-year-old has 5 days of decreased need for sleep, pressured speech, grandiosity, and risky spending that requires hospitalization. What is the most likely diagnosis?", options: ["Hypomanic episode", "Manic episode", "Cyclothymia", "Generalized anxiety disorder", "ADHD"], answerIdx: 1, explanation: ["Hospitalization or marked impairment makes this a manic episode regardless of duration.", "Hypomania does not cause marked functional impairment or require hospitalization.", "The patient should be assessed for bipolar disorder and secondary causes."] },
  { id: "q20", qid: 1020, subjectId: "psychiatry", topicId: "psych-psychosis", stem: "A patient taking clozapine develops fever and a sore throat. Which investigation is most urgent?", options: ["Serum lithium level", "Absolute neutrophil count", "Thyroid-stimulating hormone", "Creatine kinase only", "Urine toxicology"], answerIdx: 1, explanation: ["Clozapine can cause severe neutropenia and agranulocytosis.", "Fever or sore throat warrants urgent assessment of the absolute neutrophil count.", "Medication management should follow the result and local monitoring protocol."] },
  { id: "q21", qid: 1021, subjectId: "psychiatry", topicId: "psych-substance", stem: "A patient who uses opioids is unresponsive with pinpoint pupils and a respiratory rate of 6 per minute. What is the immediate antidote?", options: ["Flumazenil", "Naloxone", "N-acetylcysteine", "Atropine", "Fomepizole"], answerIdx: 1, explanation: ["The triad of reduced consciousness, respiratory depression, and miosis suggests opioid toxicity.", "Naloxone reverses opioid-induced respiratory depression.", "Airway and ventilation support remain the immediate priorities."] },
  { id: "q22", qid: 1022, subjectId: "medicine", topicId: "med-cardio", stem: "A 76-year-old has exertional syncope, angina, and dyspnea. Examination reveals a harsh systolic murmur radiating to the carotids. What is the most likely diagnosis?", options: ["Mitral regurgitation", "Aortic stenosis", "Hypertrophic cardiomyopathy", "Atrial septal defect", "Aortic regurgitation"], answerIdx: 1, explanation: ["The classic symptomatic triad and carotid radiation indicate severe aortic stenosis.", "Echocardiography confirms severity and ventricular response.", "Symptomatic severe disease requires prompt valve-team assessment."] },
  { id: "q23", qid: 1023, subjectId: "medicine", topicId: "med-resp", stem: "A patient with asthma has symptoms three times weekly and wakes with cough twice monthly. Which long-term approach is preferred?", options: ["Short-acting bronchodilator alone", "An inhaled corticosteroid-containing regimen", "Daily oral prednisone", "Antibiotics as needed", "No treatment between attacks"], answerIdx: 1, explanation: ["Controller therapy containing inhaled corticosteroid reduces exacerbation risk.", "Short-acting bronchodilator monotherapy is not preferred for ongoing asthma management.", "Technique, adherence, triggers, and an action plan should be reviewed."] },
  { id: "q24", qid: 1024, subjectId: "medicine", topicId: "med-endo", stem: "A patient has weight loss, tremor, heat intolerance, and a diffusely enlarged thyroid. TSH is suppressed and free T4 is elevated. Which additional finding supports Graves disease?", options: ["Delayed reflex relaxation", "Pretibial myxedema", "Bradycardia", "Hypothermia", "Periorbital edema without eye signs"], answerIdx: 1, explanation: ["Pretibial myxedema and thyroid eye disease are characteristic extrathyroidal features of Graves disease.", "The biochemical pattern confirms primary hyperthyroidism.", "Treatment depends on patient factors and may include antithyroid medication, radioiodine, or surgery."] },
  { id: "q25", qid: 1025, subjectId: "pmch", topicId: "pmch-screening", stem: "A 52-year-old average-risk adult asks about colorectal cancer screening. Which principle should guide the discussion?", options: ["Screen only after symptoms appear", "Use shared decision-making among recommended screening options", "Colonoscopy is the only acceptable test", "Stop all screening at age 55", "Family history does not affect recommendations"], answerIdx: 1, explanation: ["Eligible average-risk adults should be offered guideline-supported screening options.", "The specific test and interval depend on current provincial guidance, benefits, harms, access, and patient preference.", "Family history may change the starting age and modality."] },
  { id: "q26", qid: 1026, subjectId: "pmch", topicId: "pmch-epi", stem: "Investigators select people with lung cancer and matched people without lung cancer, then compare prior asbestos exposure. Which study design is this?", options: ["Randomized trial", "Cohort study", "Case-control study", "Cross-sectional survey", "Ecologic study"], answerIdx: 2, explanation: ["Participants are selected based on outcome status, then prior exposure is assessed.", "This is a case-control study.", "The odds ratio is the usual measure of association."] },
  { id: "q27", qid: 1027, subjectId: "pmch", topicId: "pmch-ethics", stem: "A 15-year-old requests contraception and demonstrates a clear understanding of benefits, risks, and alternatives. She asks that her parents not be told. What is the best response?", options: ["Refuse without parental consent", "Provide confidential care if she is capable", "Notify the school", "Ask police for permission", "Disclose automatically to her parents"], answerIdx: 1, explanation: ["A mature minor who is capable can consent to health care.", "Confidentiality should be respected unless there is a serious safety concern or another legal exception.", "The clinician can encourage supportive adult involvement without making it a condition of care."] },
  { id: "q28", qid: 1028, subjectId: "surgery", topicId: "surg-trauma", stem: "After blunt abdominal trauma, a stable patient has left upper quadrant pain and referred pain to the left shoulder. Which organ is most likely injured?", options: ["Liver", "Spleen", "Pancreas", "Right kidney", "Bladder"], answerIdx: 1, explanation: ["Left upper quadrant pain with Kehr sign suggests splenic injury and diaphragmatic irritation.", "Hemodynamic status directs the urgency and management approach.", "A stable patient is generally assessed with contrast-enhanced CT."] },
  { id: "q29", qid: 1029, subjectId: "surgery", topicId: "surg-abdo", stem: "A 44-year-old has steady right upper quadrant pain, fever, and a positive Murphy sign. Ultrasound shows gallstones and gallbladder wall thickening. What is the diagnosis?", options: ["Biliary colic", "Acute cholecystitis", "Acute pancreatitis", "Ascending cholangitis", "Peptic ulcer disease"], answerIdx: 1, explanation: ["Persistent pain, systemic inflammation, Murphy sign, and ultrasound changes indicate acute cholecystitis.", "Biliary colic causes transient pain without inflammatory findings.", "Early surgical assessment and appropriate antibiotics are typically indicated."] },
  { id: "q30", qid: 1030, subjectId: "surgery", topicId: "surg-postop", stem: "A postoperative patient suddenly develops pleuritic chest pain, dyspnea, tachycardia, and an oxygen saturation of 88%. What diagnosis must be considered first?", options: ["Atelectasis", "Pulmonary embolism", "Wound infection", "Urinary retention", "Ileus"], answerIdx: 1, explanation: ["Sudden hypoxemia, pleuritic pain, and tachycardia after surgery are concerning for pulmonary embolism.", "Assessment and treatment urgency depend on hemodynamic stability.", "Postoperative venous thromboembolism prevention is an important risk-reduction measure."] },
];

export const questionStatuses: Record<string, QuestionStatus> = Object.fromEntries(
  questions.map((question, index) => [question.id, index % 7 === 0 ? "flagged" : index % 4 === 0 ? "incorrect" : index < 18 ? "correct" : "unused"])
);

export const demoSession: Session = { id: "demo", mode: "tutor", questionIds: questions.slice(0, 20).map((q) => q.id), createdAt: "2026-08-24T15:00:00Z" };

export const recentSessions: Session[] = [
  { id: "session-104", mode: "tutor", questionIds: questions.slice(0, 20).map((q) => q.id), createdAt: "2026-08-23T18:10:00Z", finishedAt: "2026-08-23T18:38:00Z" },
  { id: "session-103", mode: "timed", questionIds: questions.slice(4, 19).map((q) => q.id), createdAt: "2026-08-22T13:30:00Z", finishedAt: "2026-08-22T13:49:00Z", secondsPerQuestion: 90 },
  { id: "session-102", mode: "tutor", questionIds: questions.slice(10, 20).map((q) => q.id), createdAt: "2026-08-20T21:00:00Z", finishedAt: "2026-08-20T21:19:00Z" },
  { id: "session-101", mode: "timed", questionIds: questions.slice(20, 30).map((q) => q.id), createdAt: "2026-08-18T16:15:00Z", finishedAt: "2026-08-18T16:28:00Z", secondsPerQuestion: 90 },
];

export const demoAttempts: Attempt[] = demoSession.questionIds.map((questionId, index) => ({
  questionId,
  sessionId: "demo",
  chosenIdx: index % 5 === 0 ? null : index % 4,
  correct: index % 4 !== 0 && index % 5 !== 0,
  timeMs: 46000 + index * 2400,
  createdAt: `2026-08-24T15:${String(index).padStart(2, "0")}:00Z`,
}));

const subjectStats = [
  { subjectId: "pediatrics", attempted: 162, correct: 127, avgTimeMs: 71000 },
  { subjectId: "psychiatry", attempted: 111, correct: 88, avgTimeMs: 64000 },
  { subjectId: "medicine", attempted: 104, correct: 71, avgTimeMs: 79000 },
  { subjectId: "pmch", attempted: 93, correct: 72, avgTimeMs: 61000 },
  { subjectId: "surgery", attempted: 17, correct: 11, avgTimeMs: 84000 },
];

export const topicStats: TopicStats[] = topics.map((topic, index) => ({
  topicId: topic.id,
  attempted: 15 + ((index * 11) % 42),
  correct: 8 + ((index * 7) % 25),
  avgTimeMs: 54000 + ((index * 5900) % 42000),
}));

export const dashboardStats: DashboardStats = {
  totalQuestions: subjects.reduce((sum, subject) => sum + subject.questionCount, 0),
  attempted: 487,
  correct: 369,
  streakDays: 9,
  subjects: subjectStats,
  weakestTopics: [topicStats[14], topicStats[8], topicStats[12], topicStats[6]],
  activity: Array.from({ length: 84 }, (_, index) => {
    const date = new Date(Date.UTC(2026, 5, 2 + index));
    const attempted = index % 7 === 0 ? 0 : (index * 7) % 26;
    return { date: date.toISOString().slice(0, 10), attempted, correct: Math.round(attempted * (0.62 + (index % 4) * 0.05)) };
  }),
};
